repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.10.7"
    hooks:
    -   id: uv-lock

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
    -   id: trailing-whitespace
        exclude: README
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/gitleaks/gitleaks
    rev: "v8.30.0"
    hooks:
    -   id: gitleaks

-   repo: https://github.com/PyCQA/bandit
    rev: "1.9.4"
    hooks:
    -   id: bandit
        args:
        -   "-c"
        -   "pyproject.toml"

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.4"
    hooks:
    -   id: ruff-format
    -   id: ruff-check
        args:
        -   "--exit-non-zero-on-fix"

-   repo: https://github.com/pycqa/pylint
    rev: "v4.0.5"
    hooks:
    -   id: pylint
        additional_dependencies:
        -   "dependency-injector>=4.48.1"
        -   "fastapi==0.116.1"
        -   "joblib>=1.5.1"
        -   "pydantic-settings>=2.10.1"
        -   "scikit-learn>=1.7.1"
        -   "uvicorn[standard]==0.35.0"
        -   "requests>=2.32.4"
        -   "streamlit>=1.48.0"
        -   "pylint-pydantic>=0.3.5"
        -   "polyfactory>=2.22.2"
        -   "pytest==8.4.1"
        -   "pytest-cov==6.2.1"
        -   "pytest-recording==0.13.4"
        -   "syrupy==4.9.1"
        -   "py-automapper>=2.2.0"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
    -   id: mypy
        additional_dependencies:
        -   "dependency-injector>=4.48.1"
        -   "fastapi==0.116.1"
        -   "joblib>=1.5.1"
        -   "joblib-stubs==1.5.0.1.20250510"
        -   "pydantic-settings>=2.10.1"
        -   "scikit-learn>=1.7.1"
        -   "uvicorn[standard]==0.35.0"
        -   "requests>=2.32.4"
        -   "streamlit>=1.48.0"
        -   "types-requests"
        -   "pytest==8.4.1"
        -   "pytest-cov==6.2.1"
        -   "pytest-recording==0.13.4"
        -   "syrupy==4.9.1"
        -   "polyfactory>=2.22.2"
        -   "py-automapper>=2.2.0"
        -   "git+https://github.com/microsoft/python-type-stubs.git"

-   repo: https://github.com/nbQA-dev/nbQA
    rev: "1.9.1"
    hooks:
    -   id: nbqa-ruff

    -   id: nbqa-pylint
        additional_dependencies:
        -   "pylint==3.3.8"
        -   "dependency-injector>=4.48.1"
        -   "fastapi==0.116.1"
        -   "joblib>=1.5.1"
        -   "pydantic-settings>=2.10.1"
        -   "scikit-learn>=1.7.1"
        -   "uvicorn[standard]==0.35.0"
        -   "jupyter==1.1.1"
        -   "requests>=2.32.4"
        -   "streamlit>=1.48.0"
        -   "pylint-pydantic>=0.3.5"

    -   id: nbqa-mypy
        additional_dependencies:
        -   "mypy==1.15.0"
        -   "dependency-injector>=4.48.1"
        -   "fastapi==0.116.1"
        -   "joblib>=1.5.1"
        -   "joblib-stubs==1.5.0.1.20250510"
        -   "pydantic-settings>=2.10.1"
        -   "scikit-learn>=1.7.1"
        -   "uvicorn[standard]==0.35.0"
        -   "jupyter==1.1.1"
        -   "requests>=2.32.4"
        -   "streamlit>=1.48.0"
        -   "types-requests"
        -   "pytest==8.4.1"
        -   "pytest-cov==6.2.1"
        -   "pytest-recording==0.13.4"
        -   "syrupy==4.9.1"
        -   "polyfactory>=2.22.2"
        -   "py-automapper>=2.2.0"
        -   "git+https://github.com/microsoft/python-type-stubs.git"

-   repo: https://github.com/kynan/nbstripout
    rev: "0.9.1"
    hooks:
    -   id: nbstripout

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.24.0"
    hooks:
    -   id: commitlint
        stages:
        -   commit-msg
        additional_dependencies:
        -   "@commitlint/config-conventional"
        args:
        -   "--config=.commitlintrc.json"
