exclude: _build

repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/gitleaks/gitleaks
    rev: "v8.23.3"
    hooks:
    -   id: gitleaks

        # - repo: https://github.com/PyCQA/bandit
        #   rev: "1.7.10"
        #   hooks:
        #     - id: bandit

-   repo: https://github.com/gauge-sh/tach-pre-commit
    rev: v0.25.6
    hooks:
    -   id: tach

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.6"
    hooks:
    -   id: ruff-format
    -   id: ruff
        args:
        -   "--exit-non-zero-on-fix"

-   repo: https://github.com/pycqa/pylint
    # Cannot be replaced by ruff until https://github.com/astral-sh/ruff/issues/970 is closed
    rev: "v3.3.4"
    hooks:
    -   id: pylint
        additional_dependencies:
        -   "google-cloud-firestore==2.18.0"
        -   "pydantic==2.9.2"
        -   "pyyaml==6.0.2"
        -   "pytest==8.3.3"
        -   "requests==2.32.3"
        -   "requests-mock==1.12.1"
        -   "polyfactory==2.18.1"
        -   "syrupy==4.8.0"
        -   "fastapi-login==1.10.3"
        -   "fastapi[standard]==0.115.6"
        -   "authlib==1.4.0"
        -   "dependency-injector==4.45.0"
        -   "pydantic-settings==2.7.1"
        -   "pytest-lazy-fixtures==1.1.1"
        -   "mypy==1.14.1"
        -   "intentguard==2.0.3"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
    -   id: mypy
        exclude: ^app/views/templates/books
        additional_dependencies:
        -   "pydantic==2.9.2"
        -   "pyyaml==6.0.2"
        -   "pytest==8.3.3"
        -   "types-requests==2.32.0.20240914"
        -   "types-PyYAML==6.0.12.20240917"
        -   "polyfactory==2.18.1"
        -   "syrupy==4.8.0"
        -   "fastapi-login==1.10.3"
        -   "fastapi[standard]==0.115.6"
        -   "authlib==1.4.0"
        -   "dependency-injector==4.45.0"
        -   "pydantic-settings==2.7.1"
        -   "pytest-lazy-fixtures==1.1.1"
        -   "mypy-exhaustive-check==1.0.0"
        -   "intentguard==2.0.3"

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.21.0"
    hooks:
    -   id: commitlint
        stages:
        -   commit-msg
        additional_dependencies:
        -   "@commitlint/config-conventional"
        args:
        -   "--config=.commitlintrc.json"